name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

    - name: Laravel Rsync Deploy
      # You may pin to the exact commit or the version.
      # uses: SHSharkar/Laravel-Rsync-Deploy@5a5d522c58e04d183842e98886164bcc86298dbe
      uses: SHSharkar/Laravel-Rsync-Deploy@v1.0.0
      with:
        # Server SSH Private Key
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        # Remote Host or IP
        REMOTE_HOST: ${{ secrets.DOMAIN }}
        # Remote Host Port
        REMOTE_HOST_PORT: 22
        # Remote User
        REMOTE_USER: ${{ secrets.USER }}
        # Target directory
        TARGET_DIRECTORY: ${{ secrets.PATH_DIR }}
